### ISSUE TITLE
[feature request] allow set prefetch on dispatcher

### ISSUE THREAD

**Issue by cheskayang** [knative-sandbox/eventing-rabbitmq#329]
right now, the prefetch on dispatcher is set to 1. This seems to be very restrictive, especially for long-running consumers.

I'm wondering why 1 is chosen?

event with keda to scale it based on the number of messages, it still seems inefficient.

Is there a plan to allow set the prefetch count or increase the default?

thx!

**Comment by vaikas** [comment]
You mean here:
https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/cmd/dispatcher/main.go#L51

Is this something that would be enough to specify at the Broker level?  Since dispatcher is for each Trigger, being able to configure it would mean changing the API and that won't be doable in the near future due to v1 work. However, adding that configuration option and plumbing that into a dispatcher seems like it would be fairly straight forward.

As far as changing the default, I'm not sure if there are any downsides to just changing the default from 1, I'm not sure why the value was chosen honestly. So changing that to something else seems reasonable too.

**Comment by cheskayang** [comment]
@vaikas thx for the quick response! Right, I'm referring to the code you linked.

I think in the long run, it probably makes the most sense to allow flexibility on the trigger level.

But if we can allow the config on the broker level in the short run, I think it would offer a lot of flexibilities, which is good enough
