### ISSUE TITLE
Add multiple options for performance in the brokers/source

### ISSUE THREAD

**Issue by gabo1208** [knative-sandbox/eventing-rabbitmq#516]
**Problem**
To make RabbitMQ's integration with Knative more performant, multiple queues or quorum queues should be an option or the default when creating Brokers and Source for the msg processing to be faster

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Developers

**Exit Criteria**
A decision on what to use and a clear performance improvement in doing so

**Additional context (optional)**
we could spin one queue per thread or use quorum queues

**Comment by gabo1208** [comment]
cc @gvmw @embano1 and any other folks that were talking about performance, queues defaults and multiple queues in threads. Here we can follow this up

**Comment by xtreme-sameer-vohra** [comment]
Hey @gabo1208 
Is this referring to something different than https://github.com/knative-sandbox/eventing-rabbitmq/issues/518 ? If so, could you add provide more context as I am not sure I understand 🤔

**Comment by gabo1208** [comment]
Just the multi queue for the source/brokers, not as broad as the #518 (was something @embano1 said in a thread that i dont want to get lost, maybe i can close this one in favour or @gvmw's issue)

**Comment by embano1** [comment]
Ah, this goes back to allowing for partitioning logic. The example given was to support one or multiple source queues for a `BrokerSource` and route them to multiple (created) queues in the `Broker` based on a partitioning key. Since we currently only have one `dipatcher` per trigger/queue this could lead to growing backlog if ingestion rate is high without further parallelization. 

Alternative would be to allow for multiple dispatchers (work queue pattern) draining from the broker queue.

**Comment by gabo1208** [comment]
Closing this one since the discussion is already settled :)
