### ISSUE TITLE
Persistent messages

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-rabbitmq#546]
We're using Durable queues, but we're [publishing transient messages](https://github.com/knative-sandbox/eventing-rabbitmq/blob/e19128bf1ab043af81931004e73a3acd1e90cf68/cmd/ingress/main.go#L142-L146) as far as I understand. This appears to be the default if you don't set [Publishing.DeliveryMode](https://pkg.go.dev/github.com/rabbitmq/amqp091-go#Publishing) to `2` ([amqp.Persistent](https://pkg.go.dev/github.com/rabbitmq/amqp091-go#pkg-constants)).

According to [this doc](https://www.rabbitmq.com/queues.html): 

> Durable queues will be recovered on node boot, including messages in them published as persistent. Messages published as transient will be discarded during recovery, even if they were stored in durable queues. 

Is this a "safe by default" we want to switch to?

**Comment by gabo1208** [comment]
I think it makes sense to add another knob in the config for this. And i agree with a safe default

**Comment by xtreme-sameer-vohra** [comment]
In case this impacts it as well - https://github.com/knative-sandbox/eventing-rabbitmq/issues/518

**Comment by gabo1208** [comment]
Going through the documentation, the logical cases are:
- If the user wants a durable queue, knative-rabbitmq should set the messages to be durable
- If the user does not want a durable queue, it doesn't matter the message setting because the messages will not persist

Future proofing regarding #518 :
Above the [Temporary Queues title,](https://www.rabbitmq.com/queues.html#temporary-queues) it says:
> Some queue types do not support transient queues. Quorum queues must be durable due to the assumptions and requirements of the underlying replication protocol, for example.

So regarding Quorum Queues (if they become default) we should also have durable messages as the default case.
