### ISSUE TITLE
Clarify if we still need `requeue` setting in the dispatcher

### ISSUE THREAD

**Issue by embano1** [knative-sandbox/eventing-rabbitmq#591]
Do we need to explicitly give the user the option to configure `requeue` if we retry by default in the CE client.

Related: #540

https://github.com/knative-sandbox/eventing-rabbitmq/blob/519852a36f044dec7d79421320b6d56d26d03400/cmd/dispatcher/main.go#L45

**Comment by xtreme-sameer-vohra** [comment]
Expectation for end users;
- Broker(dispatcher) will retry for # of retries configured in delivery spec
- After retries, will route message to DLX Or drop it if no DLX is configured

**Comment by ChunyiLyu** [comment]
Had a team discussion about whether we could ensure message ordering with the current implementation. In short, there is no way we can guarantee msg process ordering when 1) use process msgs in prefetch buffer in parallel 2) we requeue unack msgs instead of using DLE.

All messages in a prefetch (prefetch count is currently configurable) are ordered, and messages in prefetch will arrive in the same ordered as they were published. However, when we process them in parallel we lose guarantee of ordering. When we re queue msgs, the requeued msgs will go to the end of the buffer and order won’t be preserved.

To guarantee message ordering, the recommendation is 1) use 1 consumer with or without prefetch (better to use to ensure better performance compare to prefetch=1) and process incoming msgs in a single thread instead of parallel 2) always use DLE for any nack msgs instead of requeuing.

Another pattern that could work is the single active consumer pattern and set prefetch to 1. Single active consumer is a property you can set in your queues and queues ensure that there is one consumer actively consuming messages at a time. People use SAC pattern for having HA consuming apps, not for parallel msgs process.
