### ISSUE TITLE
Discussion on the RabbitMQ Broker and Source

### ISSUE THREAD

**Issue by gabo1208** [knative-sandbox/eventing-rabbitmq#609]
Here is the space to discuss and set our goals for the MVP regarding the RabbitMQ `Broker` and `Source`. Related to #408 

Goals:
Broker and Source:
- Should support FIFO ordering and have a clear case scenario where this works (Yes, the default scenario will be this for the MVP)
- Should support a High throughput mode (Yes)
    - Have all the details needed for this case to work
- We need metrics

Source:
- Have an official CloudEvent Spec implementation in the CE repo (not mandatory, we already have [the spec](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/cloudevents-protocol-spec/spec.md) and [the implementation](https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/adapter/message.go))

Current Discussion/Pain Points:
- Are we there with the at least once delivery? #540 (seems so when ditching the requeues and using the ce http retries)
- Support the connection with external RabbitMQ clusters (not necessarily managed by the RMQ's operators, almost done) 
- We need to separate the prefetch count from the parallelization factor (worker count) #615
- Define in a clear way how the FIFO mode works
- Define in a clear way how the High throughput mode
- ~We need both of these modes? Are this what the RabbitMQ team is aiming for with the eventing integration?~ Yes
- Exchanges doesn't get deleted if they are still been user (source sample case) #528 #6
- ~Requeue should be another user knob for the Broker and Source?~ #591 (for the broker case)  (Ditched requeue for the MVP)
- ~We have enough or too may user knobs already?~ The defaults help 
- What metrics we should be reporting? #576 
- ~Is a good idea to define clear and unambiguous specs for some of these points?~ We do and we have eventing ones to support them
- ~Improve performance tests (clearer tests on what is being tested)~  (Not important for the MVP)
- ~Improve the "Chaos testing"~ #563  (Not important for the MVP)
- ~We should consider implementing channels and subscriptions?~ #396 (Not important for the MVP)

**Comment by evankanderson** [comment]
I'm going to write down my understanding of the "laws of physics" as it relates to FIFO ordering, and explain how that plays out in both the `Broker` spec and Kafka implementation, based on my understanding. I'm happy to be corrected if any of this is wrong.

## FIFO queueing ([Head of Line Blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking))

For an event consumer, FIFO ordering on events in a system can only be maintained if a single event (or event batch) is processed (delivered) at a time.

Proof: consider the case where a second event is delivered while the first is still in flight. We cannot know until the first event is completed whether the second delivery is valid (because the first event processed successfully) or out-of-order (beacuse the first event processing failed and needs to be retried).

Within a batch in a given process, the same logic may be used to argue for processing a single event in the batch at a time, with the exception that you may be able to process all-or-none a parallel batch of events if you have some form of transactional storage for the event results where you can roll back all results if any delivery fails.

## Implications

In a FIFO queueing regime, the max message throughput is `1 / latency` events / sec. If you have a function which takes 5 seconds to process an event, a FIFO delivery process can only handle 12 events per minute. Given that we want to support thousands of events/second scale in Knative Eventing, clearly some requirement needs to be relaxed. The Broker spec has chosen to relax the FIFO constraint; events may be delivered in any order as long as they are delivered at least once.

### Kafka's Fudge

"But!" you say, what about Kafka? "Kafka supports high delivery throughput and in-order delivery!"

Kafka splits each topic into multiple partitions. Consumers subscribe to a Consumer Group, which tracks the last consumed offset independently for each partition. When multiple consumers subscribe to the same consumer group, the are each assigned a subset of the partitions to consume messages from. This subsetting may be updated dynamically as the number of consumers in a consumer group changes.

Within each partition, Kafka is subject to the tyranny of FIFO queueing; between partitions, there is no enforced order. Messages are assigned to partitions based on a key which may be random or may be derived from one or more fields in the data. When messages are consumed from Kafka, they will appear to be ordered within a given partition key, but will be un-ordered when considered via other fields in the message. For example, if the Kafka Broker used the `subject` and `type` fields as a partition key, all messages with the same `source` and `type` would appear FIFO, but messages with the same `subject` but different `source` attributes would not have any guaranteed order. Additionally, only one message from a given `source` and `type` could be in-flight at once, or there might be out-of-order delivery (which would be equivalent to having a `prefetch > 1` -- if you read 5 elements from a partition before advancing the consumer group, you have exactly this problem if you dispatch all 5 events and events 1,3,4,5 complete successfully).

**Comment by embano1** [comment]
> I'm happy to be corrected if any of this is wrong.

No objections on the (f)laws of FIFO. Yes, this can only be guaranteed in the two following cases:

- Single-threaded producer/consumer with max one message in-flight
- The above, but partitioned by key (for higher throughput)

The reason we did not change this behavior in the current implementation (i.e. setting prefetch >1) is that the existing behavior was in fact FIFO. This led to a number of issues reported by users in the VEBA project, e.g. backlog due to delayed processing of events.

On the other hand, it's an easy to reason about delivery mode for people not familiar with the challenges in distributed systems. Many (perhaps unknowingly/incorrectly) assume FIFO ordering in their code and perform business logic accordingly.

Example: `OrderCreated`->`OrderCancelled`

Any parallelism/concurrency involved here which would violate FIFO assumptions could lead to an invalid (and potentially disastrous) business outcome. 

So IMHO there should be a way to enforce FIFO if needed. Whether that's the default (as today in RMQ in Kn) or needs explicit configuration is something we can debate, decide and then of course clearly document.

> For example, if the Kafka Broker used the `subject` and `type` fields as a partition key, all messages with the same `source` and `type` would appear FIFO, but messages with the same `subject` but different `source` attributes would not have any guaranteed order. Additionally, only one message from a given `source` and `type` could be in-flight at once, or there might be out-of-order delivery 

I am not sure I'm following here. Did you mix up the spec properties, `subject`, `source` and `type` here by any chance?

**Comment by gabo1208** [comment]
Exactly as @embano1 said @evankanderson, just because is a fairly common use case, our default in the RabbitMQ Eventing implementations will be the FIFO behavior (at least for the MVP) and we'll support high thought put "modes" or configs :). But nice to know and pinpoint the pain points about it :).

I'll be updating this with the current status of the discussion of some of the points, any comment can be shared here too :)

**Comment by evankanderson** [comment]
Oops, I looked at the spec partway through but forgot to go back through the earlier part of the message.  That should read:

> For example, if the Kafka Broker used the source and type fields as a partition key, all messages with the same source and type would appear FIFO, but messages with the same subject but different source attributes would not have any guaranteed order. Additionally, only one message from a given source and type could be in-flight at once, or there might be out-of-order delivery

My preference would be to default to high throughput, and expose something like a `orderedBy` list property, which would list a set of CE keys where common values should be part of an ordered stream (ala Kafka's partition keys). We'd need a way to say "complete ordering" -- possibly `orderedBy: []` vs `orderedBy: nil`, though that's more subtle than I'd like. For the initial implementation, specifying any key in `orderedBy` would cause it to drop into `n=1` full FIFO mode, but we'd have the interface in place to perform higher throughput delivery later.

**Comment by embano1** [comment]
I think that is a good proposal which we can gradually add without breaking backwards-compatibility (delivery semantics) until we decide to not default to FIFO (one in flight) anymore. 

Question: do we want this only for Rabbit Streams (natural fit) or with our current implementation (handle in dispatcher/queue)?

**Comment by evankanderson** [comment]
It looks like this is all done, and we've released a GA, correct?
