### ISSUE TITLE
Support simple error codes as retry responses 

### ISSUE THREAD

**Issue by gabo1208** [knative-sandbox/eventing-rabbitmq#794]
**Problem**
When an error code is returned to the Broker, for example using golang `http.Error(...)` the broker logs a warning and does not retry sending the message. For new users that just want to test its own functions against the Broker we could be a little more friendlier and let the Broker handle both cases (a valid http error or a valid cloud event with the response code)

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Developers

**Exit Criteria**
Broker and Source accepts events and http error reponses

**Additional context (optional)**
https://knative.slack.com/archives/C017X0PFC0P/p1653832211099709

**Comment by gabo1208** [comment]
I'm currently investigating as a side project, but yes it seems off that a non empty body is giving error here

**Comment by embano1** [comment]
See for an issue which needs to be resolved before handling the proper `"failed to convert response into event: unknown Message encoding` error.
https://github.com/cloudevents/sdk-go/issues/773

**Comment by embano1** [comment]
Yes and no :) The retry issue is fixed, i.e. even on such non-CE returns the SDK retries as configured. However, I have to investigate whether the error handling can be better. For example, should we be able to log the error response instead of such a generic error message? Obviously we have to be careful to not dump MBs to stderr. 

IMHO we should also log the HTTP status (error) code unless we already do that.

Btw: I also moved away for now of my initial idea of converting the HTTP response to a proper CE.
